"""User-defined investment direction profile for daily recommendation scoring."""

from __future__ import annotations

from typing import Any


PROFILE_SOURCE_ID = "user-investment-direction-2026-07-04"


INVESTMENT_DIRECTION_THEMES: list[dict[str, Any]] = [
    {
        "key": "middle_east_reconstruction_epc",
        "label": "중동 복구 EPC·인프라",
        "points": 6,
        "keywords": [
            "middle east reconstruction",
            "middle east rebuild",
            "iran ceasefire",
            "iran reconstruction",
            "iraq reconstruction",
            "jafurah",
            "fadhili",
            "ruwais",
            "jubail",
            "al faw",
            "epc",
            "gas processing",
            "refinery",
            "petrochemical",
            "substation",
            "transmission grid",
            "port infrastructure",
            "samsung e&a",
            "samsung engineering",
            "gs e&c",
            "hyundai e&c",
            "hyundai engineering construction",
            "daewoo e&c",
            "삼성이앤에이",
            "삼성e&a",
            "삼성엔지니어링",
            "gs건설",
            "현대건설",
            "대우건설",
            "중동 복구",
            "중동 재건",
            "전후 복구",
            "이란 종전",
            "휴전",
            "사우디",
            "아람코",
            "자푸라",
            "파딜리",
            "루와이스",
            "주베일",
            "알 포",
            "정유",
            "가스처리",
            "석유화학",
            "플랜트",
            "송전망",
            "변전소",
            "항만",
            "토목",
        ],
        "reason": "중동 복구는 에너지 설비, 정유·가스 플랜트, 송전·변전, 항만·토목 발주가 먼저 움직이는 경향이 있어 과거 중동 EPC 레퍼런스가 있는 한국 건설사를 우선 점검하는 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: Samsung E&A, GS E&C, Hyundai E&C, Daewoo E&C는 중동 가스·정유·전력망·항만 레퍼런스와 전후 복구 수혜 가능성을 함께 비교",
        "risk": "체크포인트: 재건 기대감만으로 급등한 종목은 계약 규모, 발주 시점, 마진, 현장 클레임, 자재·물류·환율 리스크를 확인한 뒤 비중을 높이세요.",
    },
    {
        "key": "postbiotic_akkermansia_metabolic_health",
        "label": "포스트바이오틱스·Akkermansia 대사건강",
        "points": 6,
        "keywords": [
            "postbiotic",
            "postbiotics",
            "akkermansia",
            "akkermansia muciniphila",
            "muct",
            "pasteurized akkermansia",
            "inactivated microorganism",
            "heat-killed probiotic",
            "microbiome",
            "gut health",
            "weight maintenance",
            "weight regain",
            "obesity",
            "metabolic health",
            "insulin sensitivity",
            "glp-1",
            "rht3201",
            "ndi",
            "danone",
            "the akkermansia company",
            "ildong",
            "ildong pharmaceutical",
            "gc biopharma",
            "포스트바이오틱스",
            "사균",
            "죽은 균",
            "비활성 미생물",
            "아커만시아",
            "아커만시아 뮤시니필라",
            "저온살균",
            "마이크로바이옴",
            "장내세균",
            "장건강",
            "체중 유지",
            "체중 재증가",
            "비만",
            "대사건강",
            "인슐린 감수성",
            "건기식",
            "기능성 원료",
            "개별인정형",
            "일동제약",
            "일동홀딩스",
            "지큐랩",
            "녹십자",
        ],
        "reason": "포스트바이오틱스와 pasteurized Akkermansia는 살아있는 균보다 제형 안정성, 안전성, 유통성이 높고 비만·대사건강 보조 시장으로 확장될 수 있는 기능성 원료 투자 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향 및 Nature Medicine 2026 RCT: pasteurized Akkermansia muciniphila MucT는 24주 체중 유지기에서 위약 대비 체중 재증가를 낮춘 임상 신호를 보임",
        "risk": "체크포인트: n=90 수준의 초기 RCT라 후속 대형 임상, 원료 IP·독점권, 식약처/FDA 기능성·NDI, 실제 판매채널과 반복 구매율을 확인하세요.",
    },
    {
        "key": "ai_power_bottleneck",
        "label": "AI 전력 병목",
        "points": 8,
        "keywords": [
            "aidc",
            "bloom",
            "oracle",
            "orcl",
            "sofc",
            "fuel cell",
            "microgrid",
            "onsite power",
            "distributed power",
            "power quality",
            "gas turbine",
            "data center power",
            "800vdc",
            "데이터센터",
            "전력",
            "전력망",
            "가스터빈",
            "연료전지",
            "마이크로그리드",
            "분산전원",
            "온사이트전력",
            "전력품질",
            "bop",
            "블룸",
            "오라클",
            "두산퓨얼셀",
            "미코",
            "한선엔지니어링",
            "지엔씨에너지",
            "sk이터닉스",
            "sk에코플랜트",
        ],
        "reason": "AI 데이터센터의 병목이 GPU에서 전력 확보와 현장발전으로 확장되는 투자 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: 전력·가스·SOFC·마이크로그리드가 AI 토큰 팩토리의 1차 병목으로 분류됨",
        "risk": "체크포인트: 가스터빈 납기 단축, 전력망 접속 지연 완화, 천연가스 가격 급등 시 전력 병목 프리미엄을 재검토하세요.",
    },
    {
        "key": "repo_liquidity_stress",
        "label": "SOFR 단기자금 유동성",
        "points": 6,
        "keywords": [
            "sofr",
            "effr",
            "on rrp",
            "iorb",
            "repo",
            "sponsored repo",
            "basis trade",
            "rmp",
            "reserve management",
            "t-bill",
            "tga",
            "mmf",
            "ficc",
            "cftc",
            "funding stress",
            "레포",
            "단기자금시장",
            "베이시스 트레이드",
            "지급준비금",
            "지준",
            "국채선물",
            "헤지펀드",
            "재무부 차입",
            "딜러 밸런스",
            "유동성 스트레스",
        ],
        "reason": "SOFR 하락을 유동성 공급 증가와 레버리지 자금수요 감소로 나누어 해석하는 단기자금시장 프레임과 연결됩니다.",
        "evidence": "첨부 투자 방향: SOFR-ON RRP, SOFR-IORB, TGA, T-bill 순발행, Sponsored Repo와 CFTC 포지션을 함께 추적",
        "risk": "체크포인트: SOFR 하락이 베이시스 트레이드 축소에 따른 deleveraging이면 위험선호 강화 신호로만 해석하지 마세요.",
    },
    {
        "key": "ai_semiconductor_bottleneck",
        "label": "AI 반도체 2차 병목",
        "points": 8,
        "keywords": [
            "hbm",
            "cowos",
            "300mm",
            "wafer",
            "silicon photonics",
            "cpo",
            "advanced packaging",
            "sumco",
            "shin-etsu",
            "resonac",
            "mitsubishi gas chemical",
            "mitsui kinzoku",
            "웨이퍼",
            "실리콘 포토닉스",
            "첨단 패키징",
            "패키징",
            "신에쓰",
            "레조낙",
            "sk실트론",
            "sk하이닉스",
            "삼성전자",
            "한솔케미칼",
            "동진쎄미켐",
            "티씨케이",
        ],
        "reason": "AI 수요가 HBM·CoWoS·300mm 웨이퍼·패키징 소재 소비를 동시에 늘리는 2차 AI 수혜 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: GPU 완제품보다 웨이퍼·HBM·CoWoS·패키징 소재 같은 물리 공급망 병목을 우선 점검",
        "risk": "체크포인트: AI CAPEX 둔화, 웨이퍼 증설 가속, 엔화 강세와 소재 가격 하락 신호를 함께 확인하세요.",
    },
    {
        "key": "ai_component_substrate_test_bottleneck",
        "label": "AI 부품·기판·테스트 병목",
        "points": 8,
        "keywords": [
            "mlcc",
            "server mlcc",
            "ccl",
            "pcb",
            "abf",
            "substrate",
            "ic substrate",
            "gpu substrate",
            "test equipment",
            "ai server",
            "unimicron",
            "ibiden",
            "kinsus",
            "semco",
            "samsung electro-mechanics",
            "elite material",
            "tripod",
            "gold circuit",
            "chroma",
            "advantest",
            "hon precision",
            "yageo",
            "삼성전기",
            "적층세라믹콘덴서",
            "서버 mlcc",
            "기판",
            "서브스트레이트",
            "고급 pcb",
            "동박적층판",
            "검사 장비",
            "테스트 장비",
            "ai 서버",
        ],
        "reason": "AI 서버 수요가 MLCC, CCL/PCB, ABF·IC 서브스트레이트, 테스트 장비까지 물리 병목을 확장하는 투자 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: JPMorgan 아시아 부품 메모는 AI 서버 부품·기판·테스트 장비의 공급 타이트와 가격 전가력을 핵심 선별 기준으로 제시",
        "risk": "체크포인트: 밸류에이션 과열, 고객 증설 지연, 리드타임 정상화, 오버오더 축소와 가격 전가력 약화를 함께 확인하세요.",
    },
    {
        "key": "agentic_software_factory",
        "label": "에이전트형 소프트웨어 공장",
        "points": 7,
        "keywords": [
            "software factory",
            "factory 2.0",
            "agentic",
            "ai agents",
            "agent 365",
            "microsoft iq",
            "web iq",
            "frontier tuning",
            "copilot",
            "github",
            "foundry",
            "devops",
            "ci/cd",
            "observability",
            "incident response",
            "security automation",
            "model router",
            "sovereign intelligence",
            "on-prem ai",
            "private cloud ai",
            "dell ai factory",
            "hpe ai factory",
            "servicenow",
            "palantir",
            "crowdstrike",
            "zscaler",
            "cloudflare",
            "datadog",
            "마이크로소프트",
            "깃허브",
            "코파일럿",
            "에이전트",
            "소프트웨어 공장",
            "옵저버빌리티",
            "보안 자동화",
            "권한관리",
            "프라이빗 ai",
            "온프레미스 ai",
            "서비스나우",
            "팔란티어",
            "크라우드스트라이크",
            "지스케일러",
            "클라우드플레어",
            "데이터독",
        ],
        "reason": "기업 AI가 채팅·코딩 보조에서 권한·감사·보안이 붙은 장기 실행 워크플로 자동화로 이동하는 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: Factory 2.0·Microsoft Build·AI Factory 흐름은 DevOps, 보안, 관측성, 데이터 거버넌스와 에이전트 오케스트레이션 수요를 강화",
        "risk": "체크포인트: 파일럿이 유료 전환으로 이어지는지, 보안·감사·권한관리 예산이 붙는지, 고평가 SaaS의 NRR 둔화를 함께 확인하세요.",
    },
    {
        "key": "bci_medical_ai_sensor_rehab",
        "label": "BCI 의료AI·센서·재활",
        "points": 5,
        "keywords": [
            "bci",
            "brain computer interface",
            "neural interface",
            "neurotech",
            "eeg",
            "ecog",
            "fnirs",
            "brain signal",
            "rehab robot",
            "rehabilitation",
            "prosthetic",
            "als",
            "spinal cord",
            "wearable medical",
            "bio signal",
            "medical ai",
            "뇌-컴퓨터",
            "뇌컴퓨터",
            "뇌파",
            "뇌신호",
            "신경 인터페이스",
            "신경공학",
            "재활로봇",
            "재활",
            "보철",
            "척수손상",
            "루게릭",
            "의료ai",
            "생체신호",
            "웨어러블 의료",
        ],
        "reason": "BCI는 단일 칩 테마보다 센서, 의료 AI, 재활, 장기 임상 데이터, 데이터 거버넌스가 결합된 기능 회복 플랫폼 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: BCI는 장기 신뢰성·환자 안전·표준화·임상 검증이 핵심이며 센서·재활·의료AI 생태계로 접근",
        "risk": "체크포인트: 임상 기간, 인허가, 뇌 데이터 프라이버시, 환자별 신호 편차가 커 단기 테마 가산보다 장기 옵션으로 평가하세요.",
    },
    {
        "key": "korea_commercialization_rnd",
        "label": "국가 R&D 실증·사업화",
        "points": 5,
        "keywords": [
            "k-moonshot",
            "national r&d",
            "government r&d",
            "demonstration",
            "commercialization",
            "public procurement",
            "advanced packaging",
            "power semiconductor",
            "compound semiconductor",
            "advanced robotics",
            "industrial robotics",
            "industrial automation",
            "cyber security",
            "carbon neutrality",
            "smr",
            "battery",
            "정부 r&d",
            "국가 r&d",
            "실증",
            "사업화",
            "공공조달",
            "첨단패키징",
            "전력반도체",
            "화합물반도체",
            "첨단로봇",
            "산업용 로봇",
            "제조자동화",
            "사이버보안",
            "첨단바이오",
            "탄소중립",
            "소형모듈원전",
            "이차전지",
        ],
        "reason": "한국 정책형 R&D는 단순 테마보다 실증, 수주, 매출 전환이 확인되는 사업화 연결 기업을 우선하는 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: AI 반도체·첨단패키징·전력반도체·로봇·보안·의료AI·에너지 과제는 과제 선정 이후 실증과 상용화 확인이 중요",
        "risk": "체크포인트: 발표만 있고 수주·실증·매출 전환이 없는 테마주는 낮게 평가하고, 과제 선정·고객사·양산 일정을 함께 확인하세요.",
    },
    {
        "key": "enterprise_ai_data_cloud",
        "label": "엔터프라이즈 AI 데이터 클라우드",
        "points": 6,
        "keywords": [
            "snowflake",
            "aws",
            "amazon",
            "graviton",
            "trainium",
            "natoma",
            "cortex",
            "mcp",
            "agentic ai",
            "data cloud",
            "rpo",
            "nrr",
            "cloud marketplace",
            "enterprise ai",
            "data platform",
            "스노우플레이크",
            "아마존",
            "그래비톤",
            "나토마",
            "데이터 클라우드",
            "데이터플랫폼",
            "엔터프라이즈 ai",
            "ai 거버넌스",
            "아이덴티티",
            "권한관리",
            "agent orchestration",
            "에이전트 오케스트레이션",
        ],
        "reason": "기업 AI가 모델 학습을 넘어 데이터 플랫폼, 추론, agentic workflow, governance layer로 확산되는 투자 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: Snowflake-AWS 장기 인프라 약정은 엔터프라이즈 AI 데이터 처리와 Graviton/custom silicon 수요를 강화",
        "risk": "체크포인트: 장기 cloud commitment, AWS lock-in, AI compute 원가, product gross margin과 RPO 전환율을 확인하세요.",
    },
    {
        "key": "supply_chain_inflation",
        "label": "공급망 인플레 방어",
        "points": 5,
        "keywords": [
            "gscpi",
            "ppi",
            "stage 1",
            "stage 3",
            "stage 4",
            "inflation",
            "supply chain",
            "treasury yield",
            "oil",
            "국채금리",
            "금리",
            "인플레",
            "공급망",
            "원자재",
            "유가",
            "가격 전가",
            "가격결정력",
        ],
        "reason": "국채금리 상승과 공급망 물가 전이가 재개될 때 가격 전가력과 병목 공급자를 우선하는 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: GSCPI, PPI Stage gap, 장기금리와 유가를 매일 리스크 트리거로 점검",
        "risk": "체크포인트: 미국 30년물 금리, 유가, GSCPI, PPI Stage 1-4 격차가 동시에 상승하면 장기 듀레이션 노출을 낮추세요.",
    },
    {
        "key": "china_compute_factor",
        "label": "중국 산력 금융화",
        "points": 5,
        "keywords": [
            "maas",
            "vpp",
            "token",
            "compute exchange",
            "compute power",
            "baidu",
            "alibaba",
            "tencent",
            "산력",
            "토큰",
            "컴퓨팅 파워",
            "바이두",
            "알리바바",
            "텐센트",
            "중국 ai",
        ],
        "reason": "AI 인프라가 GPU 보유에서 산력 유통·가격 발견·API 수익화 레이어로 이동하는 방향과 연결됩니다.",
        "evidence": "첨부 투자 방향: 중국 AI 산력은 GPU보다 MaaS·AIDC·VPP·토큰 수익화 지표를 우선 확인",
        "risk": "체크포인트: 미중 AI 칩 수출 규제, 토큰 수요의 매출 전환 속도, AIDC 가동률과 전력 원가를 확인하세요.",
    },
]


def _candidate_profile_text(candidate: dict[str, Any]) -> str:
    parts: list[str] = [
        str(candidate.get("ticker") or ""),
        str(candidate.get("company_name") or ""),
    ]
    for field in ("reasons", "evidence_sources", "risk_notes", "portfolio_context", "quality_flags"):
        values = candidate.get(field)
        if isinstance(values, list):
            parts.extend(str(value or "") for value in values)
        elif values:
            parts.append(str(values))
    return " ".join(parts).lower()


def matched_investment_direction_themes(candidate: dict[str, Any]) -> list[dict[str, Any]]:
    haystack = _candidate_profile_text(candidate)
    matches: list[dict[str, Any]] = []
    for theme in INVESTMENT_DIRECTION_THEMES:
        keywords = [str(keyword).lower() for keyword in theme.get("keywords", [])]
        matched_keywords = [keyword for keyword in keywords if keyword and keyword in haystack]
        if matched_keywords:
            matches.append({**theme, "matched_keywords": matched_keywords[:5]})
    return matches


def apply_investment_direction_profile(candidate: dict[str, Any]) -> dict[str, Any]:
    """Attach the pasted investment direction profile to matching candidates."""
    themes = matched_investment_direction_themes(candidate)
    if not themes:
        return candidate

    total_points = 0
    for theme in themes[:3]:
        points = int(theme.get("points") or 0)
        total_points += points
        candidate["score"] = int(candidate.get("score") or 0) + points
        candidate.setdefault("score_components", []).append(
            {"label": f"첨부 투자 방향: {theme['label']}", "points": points}
        )
        candidate.setdefault("reasons", []).append(str(theme.get("reason") or ""))
        candidate.setdefault("evidence_sources", []).append(str(theme.get("evidence") or ""))
        candidate.setdefault("risk_notes", []).append(str(theme.get("risk") or ""))

    candidate["investment_direction_profile"] = {
        "source_id": PROFILE_SOURCE_ID,
        "summary": "중동 복구 EPC, 포스트바이오틱스·Akkermansia 대사건강, AI 물리 병목, 에이전트형 소프트웨어 공장, BCI 의료AI, 국가 R&D 사업화 프레임을 일일 추천 후보 평가에 반영",
        "matched_theme_count": len(themes),
        "score_bonus": total_points,
        "themes": [
            {
                "key": theme.get("key"),
                "label": theme.get("label"),
                "matched_keywords": theme.get("matched_keywords") or [],
            }
            for theme in themes[:4]
        ],
        "watch_triggers": [
            "중동 복구 EPC는 실제 LOI·수주 공시, 마진, 선수금, 클레임 리스크를 확인하고 기대감 급등만으로는 비중을 높이지 않음",
            "포스트바이오틱스·Akkermansia는 후속 대형 RCT, 원료 IP·독점권, 식약처/FDA 기능성 인정, 판매채널과 반복구매율을 확인",
            "미국 30년물 금리와 유가가 동시에 상승하면 장기 듀레이션·고PER 노출 축소",
            "SOFR-ON RRP 10bp 이상 또는 SOFR-IORB 양수 지속 시 repo funding pressure 재점검",
            "TGA 재축적과 T-bill 순발행 확대가 겹치면 단기 유동성 완화 신호를 낮게 평가",
            "가스터빈 납기 정상화 또는 전력망 접속 완화 시 SOFC/현장발전 프리미엄 재점검",
            "AI CAPEX 둔화 또는 웨이퍼 증설 가속 시 2차 AI 소재 비중 재검토",
            "AI 서버 부품은 MLCC·CCL/PCB·서브스트레이트·테스트 장비 리드타임과 가격 전가력을 확인",
            "에이전트 SW는 파일럿에서 유료 전환, 보안·감사·권한관리 예산, 온프레미스·프라이빗 AI 수요를 확인",
            "BCI·의료AI는 임상 적응증, FDA/MFDS 인허가, 장기 안정성 데이터, 뇌 데이터 거버넌스를 확인",
            "정부 R&D 테마는 과제 선정, 실증, 수주, 매출 전환까지 확인한 뒤 비중을 높임",
            "엔터프라이즈 AI 데이터 플랫폼은 RPO, NRR, product gross margin, cloud commitment 구조를 함께 확인",
            "GSCPI와 PPI Stage 1-4 격차가 동반 상승하면 공급망 인플레 방어 모드 강화",
        ],
    }
    candidate.setdefault("quality_flags", []).append("첨부 투자 방향 프로필 반영")
    return candidate
